### ISSUE TITLE
error since upgrading to latest version of ansible feature 2.0.4

### ISSUE THREAD

**Issue by pdeva** [devcontainers-contrib/features#281] opened 2023-01-23 19:57 UTC
We are using base image `mcr.microsoft.com/devcontainers/universal:2-focal`

Since upgrading to latest version of ansible feature (2.0.4) [released a couple days ago](https://github.com/devcontainers-contrib/features/pkgs/container/features%2Fansible), we got this error.  The last working version of ansible feature for us is `2.0.1`

```

#18 7.002 nvs remote [name] [uri]        Set or recall download base URIs
#18 7.002 
#18 7.002 A version string consists of a semantic version number or version label
#18 7.002 ("lts" or "latest"), optionally preceeded by a remote name, optionally
#18 7.002 followed by an architecture, separated by slashes.
#18 7.002 Examples: "lts", "4.6.0", "6.3.1/x86", "node/6.7.0/x64"
#18 7.002 Aliases may also be used anywhere in place of a version string.
#18 7.002 
#18 7.021 ID_LIKE=debian
#18 7.023 /usr/local/bin/featmake: line 27: apk: command not found
#18 7.028 ERROR: Feature "Ansible (via pipx)" (ghcr.io/devcontainers-contrib/features/ansible) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/ansible for help troubleshooting this error.
#18 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/ansible_4 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 127
```

**Comment by daddycocoaman** [comment] 2023-01-24 00:23
+1 for this, excepting it's affecting Nim as well. But I think the issue is the new featmake, which is trying to call apk on Ubuntu/Debian machines.

**Comment by arrrgi** [comment] 2023-01-26 06:48
Should be resolved by https://github.com/devcontainers-contrib/cli/pull/2 going forward, but a few of the existing contrib features like **pipx** and **asdf** have inherited this bug. 

I'll raise a PR for this that hopefully @danielbraun89 will see shortly that should fix both of these and any downstream features that depend on them.

**Closed** 2023-01-26 16:18 UTC

**Comment by danielbraun89** [comment] 2023-01-26 16:23
Thank you for reporting this! This is a major issue on my side Im going to further investigate how did the tests could have missed such a glaring issue :/
