### ISSUE TITLE
Cannot set aws-cdk version

### ISSUE THREAD

**Issue by raginjason** [devcontainers-contrib/features#267] opened 2023-01-17 20:59 UTC
This works:

```json
{
  "image": "mcr.microsoft.com/vscode/devcontainers/python:3.10",
  "features": {
    "ghcr.io/devcontainers-contrib/features/aws-cdk:2": { }
  }
}
```

Defining the `version` attribute does not work:

```json
{
  "image": "mcr.microsoft.com/vscode/devcontainers/python:3.10",
  "features": {
    "ghcr.io/devcontainers-contrib/features/aws-cdk:2": {
      "version": "2.60.0"
    }
  }
}
```

From the VS Code logs, it appears that version property is being interpreted as the `nvm` version not the `cdk` version:

```
[2023-01-17T20:56:42.674Z] install.sh && ./devcontainer-features-install.sh:
#0 0.205 ===========================================================================
#0 0.205 Feature       : AWS Cloud Development Kit (AWS CDK) (via npm)
#0 0.205 Description   : AWS CDK is an open-source software development framework to define cloud infrastructure in code and provision it through AWS CloudFormation.
#0 0.205 Id            : ghcr.io/devcontainers-contrib/features/aws-cdk
#0 0.205 Version       : 2.0.0
#0 0.205 Documentation : http://github.com/devcontainers-contrib/features/tree/main/src/aws-cdk
#0 0.205 Options       :
#0 0.205     VERSION="2.60.0"
#0 0.205 ===========================================================================
#0 0.747 featmake: OK
#0 0.760 resolved remote username: vscode , with home dir: /home/vscode
#0 0.760 oras not found, installing...
#0 0.767   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-01-17T20:56:42.674Z] 
#0 0.767                                  Dload  Upload   Total   Spent    Left  Speed
#0 0.768 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
#0 1.115 
 78 3298k   78 2587k    0     0  7455k      0 --:--:-- --:--:-- --:--:-- 7455k
100 3298k  100 3298k    0     0  8522k      0 --:--:-- --:--:-- --:--:-- 17.3M
#0 1.557 Downloading 26885bd163eb devcontainer-feature-npm-package.tgz
#0 1.708 Downloaded  26885bd163eb devcontainer-feature-npm-package.tgz
#0 1.710 Pulled ghcr.io/devcontainers-contrib/features/npm-package:1.0.1
#0 1.710 Digest: sha256:3c6e04c7ef2a21bfaeb8b592dad5edfd318fd26c300808e20f6055bddc5c7276
#0 1.785 Installing node and npm...
#0 1.843 Yarn already installed.
#0 1.857 NVM already installed.
#0 2.379 Version '2.60.0' not found - try `nvm ls-remote` to browse available versions.
#0 2.384 ERROR: Feature "AWS Cloud Development Kit (AWS CDK) (via npm)" (ghcr.io/devcontainers-
[2023-01-17T20:56:42.674Z] contrib/features/aws-cdk) failed to install! Look at the documentation at http://github.com/devcontainers-contrib/features/tree/main/src/aws-cdk for help troubleshooting this error.
------
[2023-01-17T20:56:42.674Z] ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/aws-cdk_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 3
[2023-01-17T20:56:42.683Z] Stop (4532 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/sx/w939d4fs4vq5d2fgr4dlzr900000gn/T/devcontainercli/container-features/0.25.2-1673988997433 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/python:3.10 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainer-aws-cdk-a7479e72755670443bac24da57cbcb6a-features -f /var/folders/sx/w939d4fs4vq5d2fgr4dlzr900000gn/T/devcontainercli/container-features/0.25.2-1673988997433/Dockerfile.extended /Users/jason.walker/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-01-17T20:56:42.683Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/sx/w939d4fs4vq5d2fgr4dlzr900000gn/T/devcontainercli/container-features/0.25.2-1673988997433 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/python:3.10 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainer-aws-cdk-a7479e72755670443bac24da57cbcb6a-features -f /var/folders/sx/w939d4fs4vq5d2fgr4dlzr900000gn/T/devcontainercli/container-features/0.25.2-1673988997433/Dockerfile.extended /Users/jason.walker/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-01-17T20:56:42.683Z]     at Aoe (/Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1355)
[2023-01-17T20:56:42.683Z]     at uT (/Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1291)
[2023-01-17T20:56:42.683Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-01-17T20:56:42.684Z]     at async Poe (/Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:2128)
[2023-01-17T20:56:42.684Z]     at async Zf (/Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:3278)
[2023-01-17T20:56:42.684Z]     at async aue (/Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15276)
[2023-01-17T20:56:42.684Z]     at async oue (/Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15030)
[2023-01-17T20:56:42.688Z] Stop (5875 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jason.walker/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/jason.walker/dev/devcontainer-aws-cdk --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jason.walker/dev/devcontainer-aws-cdk --log-level debug --log-format json --config /Users/jason.walker/dev/devcontainer-aws-cdk/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-01-17T20:56:42.688Z] Exit code 1
[2023-01-17T20:56:42.692Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/jason.walker/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jason.walker/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/jason.walker/dev/devcontainer-aws-cdk --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jason.walker/dev/devcontainer-aws-cdk --log-level debug --log-format json --config /Users/jason.walker/dev/devcontainer-aws-cdk/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-01-17T20:56:42.692Z] Exit code 1
```

Am I attempting to pin the CDK version improperly?

**Comment by danielbraun89** [comment] 2023-01-19 13:26
Thanks for reporting!
The cause of this bug is the usage of the official node feature to install it in case node/npm is not available on the machine. the VERSION env variable leaks to the node installation script and make it try to install node with version 2.60.0 which obviously does not exists. 
A fix will be released soon!

**Closed** 2023-01-21 11:58 UTC
